#!/usr/bin/env bash

## URLS
readonly ANCONDA_URL="https://repo.continuum.io/archive"
readonly MINICONDA_URL="https://repo.continuum.io/miniconda"


install_conda_local(){

## usage
usage(){
    echo "[INFO: $(date)] USAGE: install_conda.sh Miniconda3 latest ${HOME}"
}

## Installation main
main(){

## Args
local CONDA="${1}" # "Miniconda3" # Anaconda
local CONDA_VERSION="${2}" # "latest" "4.4.0" # July 2017: latest
local INSTALL_DIR="${3}" # "${HOME}"

## fixed arch to x86_64
local ARCH="Linux-x86_64" # MacOSXx86_64

## get mini- or anaconda
if [[ "${CONDA}" == "Miniconda3" ]]; then
    echo "[INFO: $(date)] Installing: ${CONDA}-${CONDA_VERSION}-${ARCH}"
    echo "[INFO: $(date)] Installation Directory: ${INSTALL_DIR}"
    local CONDA_BASH_INSTALL="${CONDA}-${CONDA_VERSION}-${ARCH}.sh"
    # install
    wget ${MINICONDA_URL}/${CONDA_BASH_INSTALL} -O ${INSTALL_DIR}/conda_install.sh && \
    bash ${INSTALL_DIR}/conda_install.sh -b -p ${INSTALL_DIR}/${CONDA} && \
    rm ${INSTALL_DIR}/conda_install.sh && \
    export PATH="${INSTALL_DIR}/${CONDA}/bin:${PATH}"
elif [[ "${CONDA}" == "Anaconda3" ]]; then
    echo "[INFO: $(date)] Installing: ${CONDA}-${CONDA_VERSION}-${ARCH}"
    echo "[INFO: $(date)] Installation Directory: ${INSTALL_DIR}"
    local CONDA_BASH_INSTALL="${CONDA}-${CONDA_VERSION}-${ARCH}.sh"
    # install
    wget ${ANCONDA_URL}/${CONDA_BASH_INSTALL} -O ${INSTALL_DIR}/conda_install.sh && \
    bash ${INSTALL_DIR}/conda_install.sh -b -p ${INSTALL_DIR}/${CONDA} && \
    rm ${INSTALL_DIR}/conda_install.sh && \
    export PATH="${INSTALL_DIR}/${CONDA}/bin:${PATH}"
else
    echo "[ERROR: $(date)] Options not recognised..exiting"
    usage
    ##exit 1
fi
}
main ${1} ${2} ${3}
}