#!/usr/bin/env bash

## Defaults
local CONDA=${1} # "Miniconda3" # Anaconda
local CONDA_VERSION=${2} # "4.4.0" # July 2017: latest
local INSTALL_DIR=${3} # "${HOME}"

## URLS
readonly ANCONDA_URL="https://repo.continuum.io/archive"
readonly MINICONDA_URL="https://repo.continuum.io/miniconda"

## fixed arch to x86_64 
readonly ARCH="Linux-x86_64" # MacOSXx86_64

## Installation main
if [[ "${CONDA}" == "Miniconda3" ]]; then
    echo "[INFO: $(date)] Installing: ${CONDA}-${CONDA_VERSION}-${ARCH}"
    echo "[INFO: $(date)] Installation Directory: ${INSTALL_DIR}"
    local CONDA_BASH_INSTALL="${CONDA}-${CONDA_VERSION}-${ARCH}.sh"
    # install
    wget ${MINICONDA_URL}/${CONDA_BASH_INSTALL} -O ${INSTALL_DIR}/conda_install.sh && \
    bash ${INSTALL_DIR}/conda_install.sh -b -p ${INSTALL_DIR}/miniconda && \
    export PATH="${INSTALL_DIR}/miniconda/bin:$PATH" && \
    rm ${INSTALL_DIR}/conda_install.sh
    
elif [[ "${CONDA}" == "Anaconda3" ]]; then
    echo "[INFO: $(date)] Installing: ${CONDA}-${CONDA_VERSION}-${ARCH}"
    echo "[INFO: $(date)] Installation Directory: ${INSTALL_DIR}"
    local CONDA_BASH_INSTALL="${CONDA}-${CONDA_VERSION}-${ARCH}.sh"
    # install
    wget ${ANCONDA_URL}/${CONDA_BASH_INSTALL} -O ${INSTALL_DIR}/conda_install.sh && \
    bash ${INSTALL_DIR}/conda_install.sh -b -p ${INSTALL_DIR}/miniconda && \
    export PATH="${INSTALL_DIR}/miniconda/bin:$PATH" && \
    rm ${INSTALL_DIR}/conda_install.sh
    
else
    echo "[ERROR: $(date)] Options not recognised..exiting"
    echo "[INFO: $(date)] USAGE: install_conda.sh Miniconda3 4.4.0 ${HOME}"
    exit 1
fi
